# Default values for ddprofiler-rc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


configMaps:
  profiler-deployment-cm-2e:
    vars:
      profiler: |-
        deployments:
          profiler-worker:
            env: "PROFILING_ENABLED: True"
            scale_factor: "0.5"
            name_suffix: "profiler"

replicaCount: 1

image:
  repository: 713544964960.dkr.ecr.us-east-1.amazonaws.com/grove/core-ddprofiler-rc
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

initConfig:
  clientType: incluster
  eksCluster:  staging-app1
  crdName: ddprof-config
  crdNamespace: default
  logLevel: DEBUG

serviceAccount:
  create: true
  annotations: {}
  name: ddprofiler-sa

roles:
  - role: ddprofiler-sa
    namespace:
      default:
        rules:
          read_write:
            apiGroups: '["", extensions, apps, crds.grove]'
            resources: '[pods, events, configmaps, deployments, deployments/extensions, deployments/scale, crds, ddprofcrds]'
            verbs: '[get, watch, list, update, create, patch, delete]'


podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}


customResources:
  ddprof-config:
    kind: DDProfCrd
    data:
      ruleType: configmap
      cmName: profiler-deployment-cm-2
      cmNamespace: default
      cmConfigTag: profiler-rc-config
