apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ddprofiler-rc.fullname" . }}
  labels:
    {{- include "ddprofiler-rc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ddprofiler-rc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ddprofiler-rc.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ddprofiler-rc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          env:
          {{- with .Values.initConfig }}
          - name: CLIENT
            value: {{ .clientType | quote }}
            {{- if .eksCluster }}
          - name: CLUSTER
            value: {{ .eksCluster | quote }}
            {{- end }}
          - name: CRD_NAME
            value: {{ $.Release.Name }}-{{ .crdName }}
          - name: CRD_NAMESPACE
            value: {{ $.Release.Namespace }}
          - name: LOGLEVEL
            value: {{ .logLevel | default "INFO" | quote }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccount: {{ .Values.serviceAccount.name }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
