{{- if hasKey .Values "customResources" }}
{{ range $key, $value := .Values.customResources }}
---
apiVersion: crds.grove/v1
kind: {{ .kind }}
metadata:
  name: {{ $.Release.Name }}-{{ $key }}
  labels:
    app: {{ $key }}
{{- if hasKey . "data" }}
{{- range $key, $value := .data }}
{{ $key }}: {{ $value }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}


