# Default values for ddprofiler-rc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Namespaces where the managed objects are
targetNameSpaces:
  - profiler-m

# It is a main config to find managed object
# It is separated from other configmaps because we have to syncronize this configmap name with crd object
# "profiler" is namespace where managed objects are
# "deployment" is type of managed object. At present only deployment type of objects is supported
# "profiler-worker" is name of deployment to be managed
config:
  name: rcconfig
  data:
    profiler-rc-config: |-
      profiler-m:
        deployments:
          profiler-worker:
            env: "PROFILING_ENABLED: True"
            scale_factor: "0.5"
            name_suffix: "profiler"

# configMaps:
# It possible to add some additional configmap


image:
  repository: DOCKERREGISTRY/grove-profiler:minikube
  imagePullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

initConfig:
  clientType: incluster
#  clientType: local
  eksCluster: staging-app1
  crdName: ddprof-rcconfig
  logLevel: DEBUG

serviceAccount:
  create: true
  annotations: {}
  name: ddprofiler-sa

roles:
  profiler: ddprofiler-sa

roles_permissions:
  apiGroups: '["", extensions, apps, crds.grove]'
  resources: '[pods, events, configmaps, deployments, deployments/extensions, deployments/scale, crds, ddprofcrds]'
  verbs: '[get, watch, list, update, create, patch, delete]'

customResources:
  ddprof-config:
    name: ddprof-rcconfig
    kind: DDProfCrd
    data:
      ruleType: configmap
      cmConfigTag: profiler-rc-config

replicaCount: 1



